directories:
  output: release
  buildResources: build
appId: com.yunjian.desktopnote
productName: 云笺阁
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  icon: electron/icons/icon.ico
  signAndEditExecutable: false
  target:
    - nsis
nsis:
  installerIcon: electron/icons/icon.ico
  uninstallerIcon: electron/icons/icon.ico
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 33.4.11
